name: Update Weather

concurrency:
  group: weather
  cancel-in-progress: false

on:
  workflow_dispatch:   # 수동 실행만

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - run: pip install requests

      - run: python weather.py
        env:
          API_KEY: ${{ secrets.WEATHER_API_KEY }}
